### ISSUE TITLE
Addition of equality is more difficult

### ISSUE THREAD

**Issue by marcbezem** [marcbezem/skolem#1]
In logic with equality, when we add a function symbol, we also add a congruence axiom for that function. This means that T_0 in Lemma 5.1 does in fact mention f. This invalidates the application of Lemma 3.4, which requires that the theory does not mention f.

**Comment by coquand** [comment]
I had in mind that T’ was T_0 together with P(x,y,f(x,y)) -and- the congruence
-rule-
 What is Lemma 3.4? I cannot find it in my version (that I attach here).

**Comment by coquand** [comment]
Sorry: for T_0 we add the congruence rule and T’ is (the new) T_0 extended with the rule P(x,y,f(x,y))
 (Still in holidays)

 What is Lemma 3.4?

 Also (just to be sure), we know by Barr’s Theorem and classical reasoning that the result is correct, right?

**Comment by coquand** [comment]
(sorry for all these messages)

 This means we -cannot- change T_0

 Maybe we can change the conclusion of Lemma 5.3
Sigma can only contain P(f(s,t),s,t) with f(s,t) in G, A
 -and-  f(s0,t0) = f(s1,t1)  with both f(s0,t0) and f(s1,t1) in G,A
??

**Comment by coquand** [comment]
What about

 if G |-_{T’} A then G, S |-_{T_0} A
where S consists of

 P(f(s,t),s,t)   with f(s,t) in G,A

or

 f(s0,t0) = f(s1,t1)

with f(s0,s1), f(t0,t1) in G,A and G |-_{T_0} si = ti

??

**Comment by coquand** [comment]
Even if we cannot prove it directly, we can mention the result and ask
for a direct proof (this is supposed to be a short paper). So the counter-example
to Wraith question should still be there and it will be interesting in any case
(I will try not to think about this problem for the coming week…)

**Comment by marcbezem** [comment]
This problem has been solved in the latest version.
